// Code generated by jpagen; DO NOT EDIT.

package warehouse

import (
	"context"
	"github.com/shubhesh07/gojpa/jpa"
	"github.com/shubhesh07/gojpa/sqlgen"
)

// RepositoryImpl implements Repository. Add hand-written methods on *RepositoryImpl in another file.
type RepositoryImpl struct {
	*jpa.Repository[MedicineWarehouse, int64]
}

var _ Repository = (*RepositoryImpl)(nil)

// NewRepository builds the repository on exec (*sql.DB or *sql.Tx).
func NewRepository(exec jpa.Executor, d sqlgen.Dialect, opts ...jpa.Option) *RepositoryImpl {
	return &RepositoryImpl{Repository: jpa.New[MedicineWarehouse, int64](exec, d, append([]jpa.Option{jpa.WithName("warehouse.Repository")}, opts...)...)}
}

// WithTx returns a copy bound to tx.
func (r *RepositoryImpl) WithTx(exec jpa.Executor) *RepositoryImpl {
	return &RepositoryImpl{Repository: r.Repository.WithTx(exec)}
}

// IncludingDeleted returns a copy that bypasses the entity's soft-delete filter.
func (r *RepositoryImpl) IncludingDeleted() *RepositoryImpl {
	return &RepositoryImpl{Repository: r.Repository.IncludingDeleted()}
}

// MedicineWarehouseFields are property names for jpa.Cond / jpa.Sort (compile-checked).
var MedicineWarehouseFields = struct {
	ID           string
	ProductCode  string
	WarehouseID  string
	Availability string
	IsSearchable string
	SuppliedByTM string
	MRP          string
	UpdatedBy    string
	UpdatedOn    string
}{ID: "ID", ProductCode: "ProductCode", WarehouseID: "WarehouseID", Availability: "Availability", IsSearchable: "IsSearchable", SuppliedByTM: "SuppliedByTM", MRP: "MRP", UpdatedBy: "UpdatedBy", UpdatedOn: "UpdatedOn"}

func (r *RepositoryImpl) CountAllInWarehouse(ctx context.Context, warehouseID int64) (int64, error) {
	return jpa.SelectScalar[int64](ctx, r, "CountAllInWarehouse", "SELECT COUNT(*) FROM medicine_warehouse_master WHERE warehouse_id = :warehouseID", map[string]any{"warehouseID": warehouseID})
}

func (r *RepositoryImpl) CountByWarehouseIdAndAvailabilityTrue(ctx context.Context, warehouseID int64) (int64, error) {
	return r.CountBy(ctx, "CountByWarehouseIdAndAvailabilityTrue", warehouseID)
}

func (r *RepositoryImpl) DeleteByProductCodeIn(ctx context.Context, codes []string) (int64, error) {
	return r.DeleteBy(ctx, "DeleteByProductCodeIn", codes)
}

func (r *RepositoryImpl) ExistsByProductCodeAndWarehouseId(ctx context.Context, code string, warehouseID int64) (bool, error) {
	return r.ExistsBy(ctx, "ExistsByProductCodeAndWarehouseId", code, warehouseID)
}

func (r *RepositoryImpl) FindByProductCodeAndWarehouseId(ctx context.Context, code string, warehouseID int64) (*MedicineWarehouse, error) {
	return r.FindOneBy(ctx, "FindByProductCodeAndWarehouseId", code, warehouseID)
}

func (r *RepositoryImpl) FindByProductCodeInAndWarehouseId(ctx context.Context, codes []string, warehouseID int64) ([]MedicineWarehouse, error) {
	return r.FindBy(ctx, "FindByProductCodeInAndWarehouseId", codes, warehouseID)
}

func (r *RepositoryImpl) FindByProductCodeInAndWarehouseIdIn(ctx context.Context, codes []string, warehouseIDs []int64) ([]MedicineWarehouse, error) {
	return r.FindBy(ctx, "FindByProductCodeInAndWarehouseIdIn", codes, warehouseIDs)
}

func (r *RepositoryImpl) FindByWarehouseIdOrderByProductCodeAsc(ctx context.Context, warehouseID int64, p jpa.Pageable) (jpa.Page[MedicineWarehouse], error) {
	return r.PageBy(ctx, "FindByWarehouseIdOrderByProductCodeAsc", p, warehouseID)
}

func (r *RepositoryImpl) FindByWarehouseIdOrderByProductCodeAscIdAsc(ctx context.Context, warehouseID int64, pos jpa.ScrollPosition) (jpa.Window[MedicineWarehouse], error) {
	return r.WindowBy(ctx, "FindByWarehouseIdOrderByProductCodeAscIdAsc", pos, warehouseID)
}

func (r *RepositoryImpl) FindLockedByProductCodeAndWarehouseId(ctx context.Context, code string, warehouseID int64, lock jpa.LockMode) (*MedicineWarehouse, error) {
	return r.FindOneBy(ctx, "FindLockedByProductCodeAndWarehouseId", code, warehouseID, lock)
}

func (r *RepositoryImpl) GetSoldCounts(ctx context.Context, codes []string) ([]SoldCount, error) {
	return jpa.Select[SoldCount](ctx, r, "GetSoldCounts", "SELECT product_code, MAX(subs_taken_count) AS subs_taken_count FROM product_sold_count WHERE product_code IN (:codes) GROUP BY product_code", map[string]any{"codes": codes})
}

func (r *RepositoryImpl) PageSoldCounts(ctx context.Context, codes []string, p jpa.Pageable) (jpa.Page[SoldCount], error) {
	return jpa.SelectPage[SoldCount](ctx, r, "PageSoldCounts", "SELECT product_code, MAX(subs_taken_count) AS subs_taken_count FROM product_sold_count WHERE product_code IN (:codes) GROUP BY product_code", "SELECT COUNT(DISTINCT product_code) FROM product_sold_count WHERE product_code IN (:codes)", p, map[string]any{"codes": codes})
}

func (r *RepositoryImpl) UpdateAvailabilityByProductCodesAndWarehouseID(ctx context.Context, availability bool, userID int64, codes []string, warehouseID int64) (int64, error) {
	return r.Exec(ctx, "UpdateAvailabilityByProductCodesAndWarehouseID", "UPDATE medicine_warehouse_master SET availability = :availability, updated_by = :userID, updated_on = NOW() WHERE product_code IN (:codes) AND warehouse_id = :warehouseID", map[string]any{"availability": availability, "userID": userID, "codes": codes, "warehouseID": warehouseID})
}
