// Code generated by jpagen; DO NOT EDIT.

package warehouse

import (
	"context"
	"database/sql"
	"github.com/shubhesh07/gojpa/jpa"
)

// RepositoryMock is a test double for Repository: set the func fields you need.
type RepositoryMock struct {
	CountFunc                                          func(ctx context.Context) (int64, error)
	CountAllInWarehouseFunc                            func(ctx context.Context, warehouseID int64) (int64, error)
	CountByWarehouseIdAndAvailabilityTrueFunc          func(ctx context.Context, warehouseID int64) (int64, error)
	DeleteAllByIDFunc                                  func(ctx context.Context, ids []int64) (int64, error)
	DeleteByIDFunc                                     func(ctx context.Context, id int64) error
	DeleteByProductCodeInFunc                          func(ctx context.Context, codes []string) (int64, error)
	ExecFunc                                           func(ctx context.Context, name string, query string, params map[string]any) (int64, error)
	ExecArgsFunc                                       func(ctx context.Context, name string, query string, args ...any) (int64, error)
	ExistsByIDFunc                                     func(ctx context.Context, id int64) (bool, error)
	ExistsByProductCodeAndWarehouseIdFunc              func(ctx context.Context, code string, warehouseID int64) (bool, error)
	FindAllFunc                                        func(ctx context.Context, sort ...jpa.Order) ([]MedicineWarehouse, error)
	FindAllByIDFunc                                    func(ctx context.Context, ids []int64) ([]MedicineWarehouse, error)
	FindByIDFunc                                       func(ctx context.Context, id int64) (*MedicineWarehouse, error)
	FindByProductCodeAndWarehouseIdFunc                func(ctx context.Context, code string, warehouseID int64) (*MedicineWarehouse, error)
	FindByProductCodeInAndWarehouseIdFunc              func(ctx context.Context, codes []string, warehouseID int64) ([]MedicineWarehouse, error)
	FindByProductCodeInAndWarehouseIdInFunc            func(ctx context.Context, codes []string, warehouseIDs []int64) ([]MedicineWarehouse, error)
	FindByWarehouseIdOrderByProductCodeAscFunc         func(ctx context.Context, warehouseID int64, p jpa.Pageable) (jpa.Page[MedicineWarehouse], error)
	FindByWarehouseIdOrderByProductCodeAscIdAscFunc    func(ctx context.Context, warehouseID int64, pos jpa.ScrollPosition) (jpa.Window[MedicineWarehouse], error)
	FindLockedByProductCodeAndWarehouseIdFunc          func(ctx context.Context, code string, warehouseID int64, lock jpa.LockMode) (*MedicineWarehouse, error)
	FindPageFunc                                       func(ctx context.Context, p jpa.Pageable) (jpa.Page[MedicineWarehouse], error)
	GetSoldCountsFunc                                  func(ctx context.Context, codes []string) ([]SoldCount, error)
	PageSoldCountsFunc                                 func(ctx context.Context, codes []string, p jpa.Pageable) (jpa.Page[SoldCount], error)
	QueryRowsFunc                                      func(ctx context.Context, name string, query string, params map[string]any, scan func(*sql.Rows) (int64, error)) error
	SaveFunc                                           func(ctx context.Context, e *MedicineWarehouse) error
	SaveAllFunc                                        func(ctx context.Context, es []*MedicineWarehouse) error
	UpdateFunc                                         func(ctx context.Context, e *MedicineWarehouse) error
	UpdateAvailabilityByProductCodesAndWarehouseIDFunc func(ctx context.Context, availability bool, userID int64, codes []string, warehouseID int64) (int64, error)
	UpdateBatchFunc                                    func(ctx context.Context, userID int64, updates []Update) (int64, error)
}

var _ Repository = (*RepositoryMock)(nil)

func (m *RepositoryMock) Count(ctx context.Context) (int64, error) {
	if m.CountFunc == nil {
		panic("RepositoryMock.Count: CountFunc not set")
	}
	return m.CountFunc(ctx)
}

func (m *RepositoryMock) CountAllInWarehouse(ctx context.Context, warehouseID int64) (int64, error) {
	if m.CountAllInWarehouseFunc == nil {
		panic("RepositoryMock.CountAllInWarehouse: CountAllInWarehouseFunc not set")
	}
	return m.CountAllInWarehouseFunc(ctx, warehouseID)
}

func (m *RepositoryMock) CountByWarehouseIdAndAvailabilityTrue(ctx context.Context, warehouseID int64) (int64, error) {
	if m.CountByWarehouseIdAndAvailabilityTrueFunc == nil {
		panic("RepositoryMock.CountByWarehouseIdAndAvailabilityTrue: CountByWarehouseIdAndAvailabilityTrueFunc not set")
	}
	return m.CountByWarehouseIdAndAvailabilityTrueFunc(ctx, warehouseID)
}

func (m *RepositoryMock) DeleteAllByID(ctx context.Context, ids []int64) (int64, error) {
	if m.DeleteAllByIDFunc == nil {
		panic("RepositoryMock.DeleteAllByID: DeleteAllByIDFunc not set")
	}
	return m.DeleteAllByIDFunc(ctx, ids)
}

func (m *RepositoryMock) DeleteByID(ctx context.Context, id int64) error {
	if m.DeleteByIDFunc == nil {
		panic("RepositoryMock.DeleteByID: DeleteByIDFunc not set")
	}
	return m.DeleteByIDFunc(ctx, id)
}

func (m *RepositoryMock) DeleteByProductCodeIn(ctx context.Context, codes []string) (int64, error) {
	if m.DeleteByProductCodeInFunc == nil {
		panic("RepositoryMock.DeleteByProductCodeIn: DeleteByProductCodeInFunc not set")
	}
	return m.DeleteByProductCodeInFunc(ctx, codes)
}

func (m *RepositoryMock) Exec(ctx context.Context, name string, query string, params map[string]any) (int64, error) {
	if m.ExecFunc == nil {
		panic("RepositoryMock.Exec: ExecFunc not set")
	}
	return m.ExecFunc(ctx, name, query, params)
}

func (m *RepositoryMock) ExecArgs(ctx context.Context, name string, query string, args ...any) (int64, error) {
	if m.ExecArgsFunc == nil {
		panic("RepositoryMock.ExecArgs: ExecArgsFunc not set")
	}
	return m.ExecArgsFunc(ctx, name, query, args...)
}

func (m *RepositoryMock) ExistsByID(ctx context.Context, id int64) (bool, error) {
	if m.ExistsByIDFunc == nil {
		panic("RepositoryMock.ExistsByID: ExistsByIDFunc not set")
	}
	return m.ExistsByIDFunc(ctx, id)
}

func (m *RepositoryMock) ExistsByProductCodeAndWarehouseId(ctx context.Context, code string, warehouseID int64) (bool, error) {
	if m.ExistsByProductCodeAndWarehouseIdFunc == nil {
		panic("RepositoryMock.ExistsByProductCodeAndWarehouseId: ExistsByProductCodeAndWarehouseIdFunc not set")
	}
	return m.ExistsByProductCodeAndWarehouseIdFunc(ctx, code, warehouseID)
}

func (m *RepositoryMock) FindAll(ctx context.Context, sort ...jpa.Order) ([]MedicineWarehouse, error) {
	if m.FindAllFunc == nil {
		panic("RepositoryMock.FindAll: FindAllFunc not set")
	}
	return m.FindAllFunc(ctx, sort...)
}

func (m *RepositoryMock) FindAllByID(ctx context.Context, ids []int64) ([]MedicineWarehouse, error) {
	if m.FindAllByIDFunc == nil {
		panic("RepositoryMock.FindAllByID: FindAllByIDFunc not set")
	}
	return m.FindAllByIDFunc(ctx, ids)
}

func (m *RepositoryMock) FindByID(ctx context.Context, id int64) (*MedicineWarehouse, error) {
	if m.FindByIDFunc == nil {
		panic("RepositoryMock.FindByID: FindByIDFunc not set")
	}
	return m.FindByIDFunc(ctx, id)
}

func (m *RepositoryMock) FindByProductCodeAndWarehouseId(ctx context.Context, code string, warehouseID int64) (*MedicineWarehouse, error) {
	if m.FindByProductCodeAndWarehouseIdFunc == nil {
		panic("RepositoryMock.FindByProductCodeAndWarehouseId: FindByProductCodeAndWarehouseIdFunc not set")
	}
	return m.FindByProductCodeAndWarehouseIdFunc(ctx, code, warehouseID)
}

func (m *RepositoryMock) FindByProductCodeInAndWarehouseId(ctx context.Context, codes []string, warehouseID int64) ([]MedicineWarehouse, error) {
	if m.FindByProductCodeInAndWarehouseIdFunc == nil {
		panic("RepositoryMock.FindByProductCodeInAndWarehouseId: FindByProductCodeInAndWarehouseIdFunc not set")
	}
	return m.FindByProductCodeInAndWarehouseIdFunc(ctx, codes, warehouseID)
}

func (m *RepositoryMock) FindByProductCodeInAndWarehouseIdIn(ctx context.Context, codes []string, warehouseIDs []int64) ([]MedicineWarehouse, error) {
	if m.FindByProductCodeInAndWarehouseIdInFunc == nil {
		panic("RepositoryMock.FindByProductCodeInAndWarehouseIdIn: FindByProductCodeInAndWarehouseIdInFunc not set")
	}
	return m.FindByProductCodeInAndWarehouseIdInFunc(ctx, codes, warehouseIDs)
}

func (m *RepositoryMock) FindByWarehouseIdOrderByProductCodeAsc(ctx context.Context, warehouseID int64, p jpa.Pageable) (jpa.Page[MedicineWarehouse], error) {
	if m.FindByWarehouseIdOrderByProductCodeAscFunc == nil {
		panic("RepositoryMock.FindByWarehouseIdOrderByProductCodeAsc: FindByWarehouseIdOrderByProductCodeAscFunc not set")
	}
	return m.FindByWarehouseIdOrderByProductCodeAscFunc(ctx, warehouseID, p)
}

func (m *RepositoryMock) FindByWarehouseIdOrderByProductCodeAscIdAsc(ctx context.Context, warehouseID int64, pos jpa.ScrollPosition) (jpa.Window[MedicineWarehouse], error) {
	if m.FindByWarehouseIdOrderByProductCodeAscIdAscFunc == nil {
		panic("RepositoryMock.FindByWarehouseIdOrderByProductCodeAscIdAsc: FindByWarehouseIdOrderByProductCodeAscIdAscFunc not set")
	}
	return m.FindByWarehouseIdOrderByProductCodeAscIdAscFunc(ctx, warehouseID, pos)
}

func (m *RepositoryMock) FindLockedByProductCodeAndWarehouseId(ctx context.Context, code string, warehouseID int64, lock jpa.LockMode) (*MedicineWarehouse, error) {
	if m.FindLockedByProductCodeAndWarehouseIdFunc == nil {
		panic("RepositoryMock.FindLockedByProductCodeAndWarehouseId: FindLockedByProductCodeAndWarehouseIdFunc not set")
	}
	return m.FindLockedByProductCodeAndWarehouseIdFunc(ctx, code, warehouseID, lock)
}

func (m *RepositoryMock) FindPage(ctx context.Context, p jpa.Pageable) (jpa.Page[MedicineWarehouse], error) {
	if m.FindPageFunc == nil {
		panic("RepositoryMock.FindPage: FindPageFunc not set")
	}
	return m.FindPageFunc(ctx, p)
}

func (m *RepositoryMock) GetSoldCounts(ctx context.Context, codes []string) ([]SoldCount, error) {
	if m.GetSoldCountsFunc == nil {
		panic("RepositoryMock.GetSoldCounts: GetSoldCountsFunc not set")
	}
	return m.GetSoldCountsFunc(ctx, codes)
}

func (m *RepositoryMock) PageSoldCounts(ctx context.Context, codes []string, p jpa.Pageable) (jpa.Page[SoldCount], error) {
	if m.PageSoldCountsFunc == nil {
		panic("RepositoryMock.PageSoldCounts: PageSoldCountsFunc not set")
	}
	return m.PageSoldCountsFunc(ctx, codes, p)
}

func (m *RepositoryMock) QueryRows(ctx context.Context, name string, query string, params map[string]any, scan func(*sql.Rows) (int64, error)) error {
	if m.QueryRowsFunc == nil {
		panic("RepositoryMock.QueryRows: QueryRowsFunc not set")
	}
	return m.QueryRowsFunc(ctx, name, query, params, scan)
}

func (m *RepositoryMock) Save(ctx context.Context, e *MedicineWarehouse) error {
	if m.SaveFunc == nil {
		panic("RepositoryMock.Save: SaveFunc not set")
	}
	return m.SaveFunc(ctx, e)
}

func (m *RepositoryMock) SaveAll(ctx context.Context, es []*MedicineWarehouse) error {
	if m.SaveAllFunc == nil {
		panic("RepositoryMock.SaveAll: SaveAllFunc not set")
	}
	return m.SaveAllFunc(ctx, es)
}

func (m *RepositoryMock) Update(ctx context.Context, e *MedicineWarehouse) error {
	if m.UpdateFunc == nil {
		panic("RepositoryMock.Update: UpdateFunc not set")
	}
	return m.UpdateFunc(ctx, e)
}

func (m *RepositoryMock) UpdateAvailabilityByProductCodesAndWarehouseID(ctx context.Context, availability bool, userID int64, codes []string, warehouseID int64) (int64, error) {
	if m.UpdateAvailabilityByProductCodesAndWarehouseIDFunc == nil {
		panic("RepositoryMock.UpdateAvailabilityByProductCodesAndWarehouseID: UpdateAvailabilityByProductCodesAndWarehouseIDFunc not set")
	}
	return m.UpdateAvailabilityByProductCodesAndWarehouseIDFunc(ctx, availability, userID, codes, warehouseID)
}

func (m *RepositoryMock) UpdateBatch(ctx context.Context, userID int64, updates []Update) (int64, error) {
	if m.UpdateBatchFunc == nil {
		panic("RepositoryMock.UpdateBatch: UpdateBatchFunc not set")
	}
	return m.UpdateBatchFunc(ctx, userID, updates)
}
