// Code generated by jpagen; DO NOT EDIT.

package main

import (
	"context"
	"database/sql"
	"github.com/shubhesh07/gojpa/jpa"
)

// ProductRepositoryMock is a test double for ProductRepository: set the func fields you need.
type ProductRepositoryMock struct {
	CountFunc                                func(ctx context.Context) (int64, error)
	CountByPriceLessThanFunc                 func(ctx context.Context, max float64) (int64, error)
	DeleteAllByIDFunc                        func(ctx context.Context, ids []int64) (int64, error)
	DeleteByCodeFunc                         func(ctx context.Context, code string) (int64, error)
	DeleteByIDFunc                           func(ctx context.Context, id int64) error
	ExecFunc                                 func(ctx context.Context, name string, query string, params map[string]any) (int64, error)
	ExecArgsFunc                             func(ctx context.Context, name string, query string, args ...any) (int64, error)
	ExistsByIDFunc                           func(ctx context.Context, id int64) (bool, error)
	FindAllFunc                              func(ctx context.Context, sort ...jpa.Order) ([]Product, error)
	FindAllByIDFunc                          func(ctx context.Context, ids []int64) ([]Product, error)
	FindByActiveTrueFunc                     func(ctx context.Context, p jpa.Pageable) (jpa.Page[Product], error)
	FindByCodeFunc                           func(ctx context.Context, code string) (*Product, error)
	FindByIDFunc                             func(ctx context.Context, id int64) (*Product, error)
	FindByNameContainingOrderByPriceDescFunc func(ctx context.Context, fragment string) ([]Product, error)
	FindPageFunc                             func(ctx context.Context, p jpa.Pageable) (jpa.Page[Product], error)
	PriceStatsFunc                           func(ctx context.Context) (*Stats, error)
	QueryRowsFunc                            func(ctx context.Context, name string, query string, params map[string]any, scan func(*sql.Rows) (int64, error)) error
	RaisePriceByCodesFunc                    func(ctx context.Context, factor float64, codes []string) (int64, error)
	SaveFunc                                 func(ctx context.Context, e *Product) error
	SaveAllFunc                              func(ctx context.Context, es []*Product) error
	UpdateFunc                               func(ctx context.Context, e *Product) error
}

var _ ProductRepository = (*ProductRepositoryMock)(nil)

func (m *ProductRepositoryMock) Count(ctx context.Context) (int64, error) {
	if m.CountFunc == nil {
		panic("ProductRepositoryMock.Count: CountFunc not set")
	}
	return m.CountFunc(ctx)
}

func (m *ProductRepositoryMock) CountByPriceLessThan(ctx context.Context, max float64) (int64, error) {
	if m.CountByPriceLessThanFunc == nil {
		panic("ProductRepositoryMock.CountByPriceLessThan: CountByPriceLessThanFunc not set")
	}
	return m.CountByPriceLessThanFunc(ctx, max)
}

func (m *ProductRepositoryMock) DeleteAllByID(ctx context.Context, ids []int64) (int64, error) {
	if m.DeleteAllByIDFunc == nil {
		panic("ProductRepositoryMock.DeleteAllByID: DeleteAllByIDFunc not set")
	}
	return m.DeleteAllByIDFunc(ctx, ids)
}

func (m *ProductRepositoryMock) DeleteByCode(ctx context.Context, code string) (int64, error) {
	if m.DeleteByCodeFunc == nil {
		panic("ProductRepositoryMock.DeleteByCode: DeleteByCodeFunc not set")
	}
	return m.DeleteByCodeFunc(ctx, code)
}

func (m *ProductRepositoryMock) DeleteByID(ctx context.Context, id int64) error {
	if m.DeleteByIDFunc == nil {
		panic("ProductRepositoryMock.DeleteByID: DeleteByIDFunc not set")
	}
	return m.DeleteByIDFunc(ctx, id)
}

func (m *ProductRepositoryMock) Exec(ctx context.Context, name string, query string, params map[string]any) (int64, error) {
	if m.ExecFunc == nil {
		panic("ProductRepositoryMock.Exec: ExecFunc not set")
	}
	return m.ExecFunc(ctx, name, query, params)
}

func (m *ProductRepositoryMock) ExecArgs(ctx context.Context, name string, query string, args ...any) (int64, error) {
	if m.ExecArgsFunc == nil {
		panic("ProductRepositoryMock.ExecArgs: ExecArgsFunc not set")
	}
	return m.ExecArgsFunc(ctx, name, query, args...)
}

func (m *ProductRepositoryMock) ExistsByID(ctx context.Context, id int64) (bool, error) {
	if m.ExistsByIDFunc == nil {
		panic("ProductRepositoryMock.ExistsByID: ExistsByIDFunc not set")
	}
	return m.ExistsByIDFunc(ctx, id)
}

func (m *ProductRepositoryMock) FindAll(ctx context.Context, sort ...jpa.Order) ([]Product, error) {
	if m.FindAllFunc == nil {
		panic("ProductRepositoryMock.FindAll: FindAllFunc not set")
	}
	return m.FindAllFunc(ctx, sort...)
}

func (m *ProductRepositoryMock) FindAllByID(ctx context.Context, ids []int64) ([]Product, error) {
	if m.FindAllByIDFunc == nil {
		panic("ProductRepositoryMock.FindAllByID: FindAllByIDFunc not set")
	}
	return m.FindAllByIDFunc(ctx, ids)
}

func (m *ProductRepositoryMock) FindByActiveTrue(ctx context.Context, p jpa.Pageable) (jpa.Page[Product], error) {
	if m.FindByActiveTrueFunc == nil {
		panic("ProductRepositoryMock.FindByActiveTrue: FindByActiveTrueFunc not set")
	}
	return m.FindByActiveTrueFunc(ctx, p)
}

func (m *ProductRepositoryMock) FindByCode(ctx context.Context, code string) (*Product, error) {
	if m.FindByCodeFunc == nil {
		panic("ProductRepositoryMock.FindByCode: FindByCodeFunc not set")
	}
	return m.FindByCodeFunc(ctx, code)
}

func (m *ProductRepositoryMock) FindByID(ctx context.Context, id int64) (*Product, error) {
	if m.FindByIDFunc == nil {
		panic("ProductRepositoryMock.FindByID: FindByIDFunc not set")
	}
	return m.FindByIDFunc(ctx, id)
}

func (m *ProductRepositoryMock) FindByNameContainingOrderByPriceDesc(ctx context.Context, fragment string) ([]Product, error) {
	if m.FindByNameContainingOrderByPriceDescFunc == nil {
		panic("ProductRepositoryMock.FindByNameContainingOrderByPriceDesc: FindByNameContainingOrderByPriceDescFunc not set")
	}
	return m.FindByNameContainingOrderByPriceDescFunc(ctx, fragment)
}

func (m *ProductRepositoryMock) FindPage(ctx context.Context, p jpa.Pageable) (jpa.Page[Product], error) {
	if m.FindPageFunc == nil {
		panic("ProductRepositoryMock.FindPage: FindPageFunc not set")
	}
	return m.FindPageFunc(ctx, p)
}

func (m *ProductRepositoryMock) PriceStats(ctx context.Context) (*Stats, error) {
	if m.PriceStatsFunc == nil {
		panic("ProductRepositoryMock.PriceStats: PriceStatsFunc not set")
	}
	return m.PriceStatsFunc(ctx)
}

func (m *ProductRepositoryMock) QueryRows(ctx context.Context, name string, query string, params map[string]any, scan func(*sql.Rows) (int64, error)) error {
	if m.QueryRowsFunc == nil {
		panic("ProductRepositoryMock.QueryRows: QueryRowsFunc not set")
	}
	return m.QueryRowsFunc(ctx, name, query, params, scan)
}

func (m *ProductRepositoryMock) RaisePriceByCodes(ctx context.Context, factor float64, codes []string) (int64, error) {
	if m.RaisePriceByCodesFunc == nil {
		panic("ProductRepositoryMock.RaisePriceByCodes: RaisePriceByCodesFunc not set")
	}
	return m.RaisePriceByCodesFunc(ctx, factor, codes)
}

func (m *ProductRepositoryMock) Save(ctx context.Context, e *Product) error {
	if m.SaveFunc == nil {
		panic("ProductRepositoryMock.Save: SaveFunc not set")
	}
	return m.SaveFunc(ctx, e)
}

func (m *ProductRepositoryMock) SaveAll(ctx context.Context, es []*Product) error {
	if m.SaveAllFunc == nil {
		panic("ProductRepositoryMock.SaveAll: SaveAllFunc not set")
	}
	return m.SaveAllFunc(ctx, es)
}

func (m *ProductRepositoryMock) Update(ctx context.Context, e *Product) error {
	if m.UpdateFunc == nil {
		panic("ProductRepositoryMock.Update: UpdateFunc not set")
	}
	return m.UpdateFunc(ctx, e)
}
