// Code generated by jpagen; DO NOT EDIT.

package main

import (
	"context"
	"github.com/shubhesh07/gojpa/jpa"
	"github.com/shubhesh07/gojpa/sqlgen"
)

// ProductRepositoryImpl implements ProductRepository. Add hand-written methods on *ProductRepositoryImpl in another file.
type ProductRepositoryImpl struct {
	*jpa.Repository[Product, int64]
}

var _ ProductRepository = (*ProductRepositoryImpl)(nil)

// NewProductRepository builds the repository on exec (*sql.DB or *sql.Tx).
func NewProductRepository(exec jpa.Executor, d sqlgen.Dialect, opts ...jpa.Option) *ProductRepositoryImpl {
	return &ProductRepositoryImpl{Repository: jpa.New[Product, int64](exec, d, append([]jpa.Option{jpa.WithName("main.ProductRepository")}, opts...)...)}
}

// WithTx returns a copy bound to tx.
func (r *ProductRepositoryImpl) WithTx(exec jpa.Executor) *ProductRepositoryImpl {
	return &ProductRepositoryImpl{Repository: r.Repository.WithTx(exec)}
}

// IncludingDeleted returns a copy that bypasses the entity's soft-delete filter.
func (r *ProductRepositoryImpl) IncludingDeleted() *ProductRepositoryImpl {
	return &ProductRepositoryImpl{Repository: r.Repository.IncludingDeleted()}
}

// ProductFields are property names for jpa.Cond / jpa.Sort (compile-checked).
var ProductFields = struct {
	ID        string
	Code      string
	Name      string
	Price     string
	Active    string
	UpdatedOn string
}{ID: "ID", Code: "Code", Name: "Name", Price: "Price", Active: "Active", UpdatedOn: "UpdatedOn"}

func (r *ProductRepositoryImpl) CountByPriceLessThan(ctx context.Context, max float64) (int64, error) {
	return r.CountBy(ctx, "CountByPriceLessThan", max)
}

func (r *ProductRepositoryImpl) DeleteByCode(ctx context.Context, code string) (int64, error) {
	return r.DeleteBy(ctx, "DeleteByCode", code)
}

func (r *ProductRepositoryImpl) FindByActiveTrue(ctx context.Context, p jpa.Pageable) (jpa.Page[Product], error) {
	return r.PageBy(ctx, "FindByActiveTrue", p)
}

func (r *ProductRepositoryImpl) FindByCode(ctx context.Context, code string) (*Product, error) {
	return r.FindOneBy(ctx, "FindByCode", code)
}

func (r *ProductRepositoryImpl) FindByNameContainingOrderByPriceDesc(ctx context.Context, fragment string) ([]Product, error) {
	return r.FindBy(ctx, "FindByNameContainingOrderByPriceDesc", fragment)
}

func (r *ProductRepositoryImpl) PriceStats(ctx context.Context) (*Stats, error) {
	return jpa.SelectOne[Stats](ctx, r, "PriceStats", "SELECT COUNT(*) AS n, MIN(price) AS min_price, MAX(price) AS max_price FROM product WHERE active = TRUE", map[string]any{})
}

func (r *ProductRepositoryImpl) RaisePriceByCodes(ctx context.Context, factor float64, codes []string) (int64, error) {
	return r.Exec(ctx, "RaisePriceByCodes", "UPDATE product SET price = price * :factor WHERE code IN (:codes)", map[string]any{"factor": factor, "codes": codes})
}
